# Generated by Django 5.2.5 on 2025-08-25 02:06

import api.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', api.manager.CustomUserManager()),
            ],
        ),
    ]
