# Generated by Django 5.2.5 on 2025-08-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bloodrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
