# Generated by Django 5.2.5 on 2025-09-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bloodrequest_status_donation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='donor',
            new_name='is_donor',
        ),
    ]
